---
ansible: [uv, yamllint]
biome: [js-pm]
bruno: [js-pm]
bun: []
corepack: [fnm, nvm]
depcheck: [js-pm]
docker: []
eslint: [js-pm]
fnm: []
gh: []
git: [gh]
go: []
hadolint: []
js-pm: [bun, npm, pnpm, yarn]
knip: [js-pm]
npm: [corepack, fnm, nvm]
nvm: []
pnpm: [corepack, fnm, nvm]
prettier: [js-pm]
python: []
sqlfluff: [uv]
staticcheck: [go]
stylelint: [js-pm]
typescript: [js-pm]
uv: []
yamllint: [uv]
yarn: [corepack, fnm, nvm]
