biome:      [js-pm]
bun:        []
corepack:   [fnm, nvm]
depcheck:   [js-pm]
eslint:     [js-pm]
fnm:        []
gh:         []
git:        [gh]
go:         []
js-pm:      [bun, npm, pnpm, yarn]
knip:       [js-pm]
npm:        [corepack, fnm, nvm]
nvm:        []
pnpm:       [corepack, fnm, nvm]
prettier:   [js-pm]
staticcheck: [go]
stylelint:  [js-pm]
typescript: [js-pm]
yarn:       [corepack, fnm, nvm]
